name: Build and Scan Images

on:
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  build-scan:
    name: ğŸ›¡ï¸ Build and Scan
    runs-on: ubuntu-latest
    permissions:
      security-events: write # Required to upload SARIF results to GitHub Security tab
      actions: read
      contents: read
    steps:
      - name: â¬‡ï¸ Check out code
        uses: actions/checkout@v5

      - name: Manual Trivy Setup
        uses: aquasecurity/setup-trivy@v0.2.3
        with:
          cache: true
          version: v0.66.0

      - name: ğŸ—ï¸ Build Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          tags: juice-shop:local
          load: true

      - name: ğŸ”¬ Run Trivy vulnerability scanner in image mode (Container Scan)
        uses: aquasecurity/trivy-action@0.28.0
        with:
          scan-type: "image"
          image-ref: "juice-shop:local"
          exit-code: "1"
          ignore-unfixed: true
          severity: "CRITICAL,HIGH"
          format: "sarif"
          output: "trivy-image-results.sarif"
          skip-setup-trivy: true

      - name: ğŸ“¤ Upload Trivy image scan results
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: "trivy-image-results.sarif"
          category: trivy-image
